Feat/set up repo
digicatapult/nice-fetch-ai-adapter pull request #4
Opened 2024-05-20 13:37 UTC by Ellenn-A

# Changes 
- set up. python repo 
- Set up lint & test in CI
- added required endpoints as per ticket 

### Ticket: 
- https://digicatapult.atlassian.net/browse/VR-88

2024-05-20 13:52 UTC, jonmattgray commented on Dockerfile
> +# LABEL org.opencontainers.image.source=https://github.com/CDECatapult/soniclabs-resultsmanager
comment to delete

2024-05-20 13:54 UTC, jonmattgray commented on app/routes/posts.py
> +peerUrl = "http://localhost:3001/api"
have as envs? example from other python repo https://github.com/CDECatapult/soniclabs-resultsmanager/blob/main/app/core/config.py

2024-05-21 07:42 UTC, dblane-digicatapult requested changes

2024-05-21 07:42 UTC, dblane-digicatapult commented on .github/workflows/ISSUE_TEMPLATE/bug_report.md
> +Have you read nice-fetch-ai-adapter's Code of Conduct? By filing an Issue, you are expected to comply with it, including treating everyone with respect: https://github.com/digicatapult/nice-fetch-ai-
```suggestion
Have you read nice-fetch-ai-adapter's Code of Conduct? By filing an Issue, you are expected to comply with it, including treating everyone with respect: https://github.com/digicatapult/nice-fetch-ai-adapter/blob/main/CODE_OF_CONDUCT.md
```

2024-05-21 07:42 UTC, dblane-digicatapult commented on .github/workflows/ISSUE_TEMPLATE/feature_request.md
> +Have you read nice-fetch-ai-adapter's Code of Conduct? By filing an Issue, you are expected to comply with it, including treating everyone with respect: https://github.com/digicatapult/nice-fetch-ai-
```suggestion
Have you read nice-fetch-ai-adapter's Code of Conduct? By filing an Issue, you are expected to comply with it, including treating everyone with respect: https://github.com/digicatapult/nice-fetch-ai-adapter/blob/main/CODE_OF_CONDUCT.md
```

2024-05-21 07:42 UTC, dblane-digicatapult commented on CONTRIBUTING.md
> +Bugs are tracked as [GitHub issues](https://guides.github.com/features/issues/). Create an issue on that repository and provide the following information by filling in [the template](https://github.c
```suggestion
Bugs are tracked as [GitHub issues](https://guides.github.com/features/issues/). Create an issue on that repository and provide the following information by filling in [the template](https://github.com/digicatapult/nice-fetch-ai-adapter/blob/main/.github/ISSUE_TEMPLATE/bug_report.md).
```

2024-05-21 10:20 UTC, msterle reviewed
lgtm

2024-05-21 10:23 UTC, dblane-digicatapult approved these changes

2024-05-21 10:34 UTC, merged